### ISSUE TITLE
test broken on master

### ISSUE THREAD

**Issue by kumavis** [musteka-la/kitsunet-js#30]
```
kitsunet-js on  master [!] is 📦 v0.0.1 via ⬢ v10.15.3 took 58s 
➜ npm test

> kitsunet@0.0.1 test /home/xyz/Development/kitsunet-js
> aegir test

Test Node.js
Warning: Could not find any test files matching pattern: test/node.js


  kitsunet rpc
    1) should encode IDENTIFY message
    2) should encode SLICE_ID message
    3) should encode SLICES message
    4) should encode HEADERS message
    5) should encode LATEST_BLOCK message
    6) should encode NODE_TYPE message

  slice manager
    7) should track slices
    8) should untrack slices
    9) should store slices
    ✓ should get slice by id
    ✓ should get latest slice
    ✓ should get slice by block
    ✓ should start
    ✓ should stop

  slice
    ✓ should construct a valid slice id
    ✓ should construct a valid slice from string id
    ✓ should construct slice from buffer
    ✓ should construct slice from string
    ✓ should construct slice from object

  sliced trie
    ✓ should retrieve key from trie


  11 passing (61ms)
  9 failing

  1) kitsunet rpc
       should encode IDENTIFY message:
     TypeError: Cannot read property 'identify' of undefined
      at Context.it (test/kitsunet-rpc.spec.js:45:55)

  2) kitsunet rpc
       should encode SLICE_ID message:
     TypeError: Cannot read property 'sliceIds' of undefined
      at Context.it (test/kitsunet-rpc.spec.js:65:55)

  3) kitsunet rpc
       should encode SLICES message:
     TypeError: Cannot read property 'slices' of undefined
      at Context.it (test/kitsunet-rpc.spec.js:85:53)

  4) kitsunet rpc
       should encode HEADERS message:
     TypeError: Cannot read property 'headers' of undefined
      at Context.it (test/kitsunet-rpc.spec.js:105:54)

  5) kitsunet rpc
       should encode LATEST_BLOCK message:
     TypeError: Cannot read property 'latestBlock' of undefined
      at Context.it (test/kitsunet-rpc.spec.js:125:58)

  6) kitsunet rpc
       should encode NODE_TYPE message:
     TypeError: Cannot read property 'type' of undefined
      at Context.it (test/kitsunet-rpc.spec.js:145:51)

  7) slice manager
       should track slices:
     AssertionError [ERR_ASSERTION]: slicesStore should be supplied
      at new SliceManager (src/slice-manager.js:18:5)
      at Context.it (test/slice-manager.spec.js:34:26)

  8) slice manager
       should untrack slices:
     AssertionError [ERR_ASSERTION]: slicesStore should be supplied
      at new SliceManager (src/slice-manager.js:18:5)
      at Context.it (test/slice-manager.spec.js:57:26)

  9) slice manager
       should store slices:
     AssertionError [ERR_ASSERTION]: slicesStore should be supplied
      at new SliceManager (src/slice-manager.js:18:5)
      at Context.it (test/slice-manager.spec.js:73:26)



Command failed: mocha --ui bdd --timeout 5000 --colors --exit test/node.js test/**/*.spec.js
null
null
npm ERR! Test failed.  See above for more details.
```

we should setup CI? related https://github.com/musteka-la/kitsunet-js/issues/12

**Comment by dryajov** [comment]
Test are outdated and are rewitten in #29.

Definitely on CI. I'll set something up in the upcoming days, after #29 is merged.
